name: Revision Automatica - EDA

on:
  pull_request:
    branches: [ "main", "master" ]

jobs:
  evaluacion:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Obtener codigo del alumno
        uses: actions/checkout@v4

      - name: 2. Limpieza preventiva
        run: make clean

      - name: 3. Intentar Compilar
        run: make

      - name: 4. Ejecutar Pruebas Unitarias
        run: ./tests 

      - name: 5. Limpieza final
        run: make clean
        if: always()
