name: Revision Automatica - EDA  # Nombre que aparecerá en GitHub

on:
  pull_request:
    branches: [ "main", "master" ] # Se activa cuando alguien envía código a estas ramas

jobs:
  evaluacion:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Obtener codigo del alumno
        uses: actions/checkout@v4

      - name: 2. Limpieza preventiva
        run: make clean

      - name: 3. Intentar Compilar
        run: make

      - name: 4. Ejecutar Pruebas Unitarias
        # Asumiendo que el Makefile genera un ejecutable llamado 'tests'
        # o que tienes un comando para correr la batería de pruebas.
        run: ./tests 

      - name: 5. Limpieza final
        run: make clean
        if: always() # Esto asegura que se limpie incluso si la compilación o los tests fallan
